on: push
jobs: 
    build-node:
        runs-on: ubuntu-latest
        container: node:18
        steps:
            - run: node --verion
            - run: npm --verion
            - uses: actions/checkout@v3
            - run: npm install
            - run: node main.js
